name: Weather Engine Daily Pipeline


on:
  schedule:
    # Runs daily at 7:45 PM IST
    # GitHub uses UTC time
    - cron: "15 14 * * *"


  workflow_dispatch:


jobs:

  forecast:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-cron.txt


      - name: Run Weather Engine
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
          APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

        run: |
          python scripts/master_script.py