name: Weather Engine Daily Pipeline

on:
  schedule:
    # 7:45 PM IST = 2:15 PM UTC
    - cron: "15 14 * * *"

  workflow_dispatch:

jobs:
  forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Production Branch
        uses: actions/checkout@v4
        with:
          ref: production


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-cron.txt

      - name: Check Environment
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          echo "EMAIL_ADDRESS exists"
          test -n "$EMAIL_ADDRESS"
          test -n "$EMAIL_PASSWORD"
          

      - name: Run Weather Engine Pipeline
        env:
          PYTHONPATH: ${{ github.workspace }}

          DATABASE_URL: ${{ secrets.DATABASE_URL }}

          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}

          APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

        run: |
          python scripts/master_script.py
